### PR TITLE
Fix indexing error

### PR DESCRIPTION
**Pull request by Korosensei42**
This should fix the new Error that occured and was described in Issue #50

### CODE REVIEW

**Comment by Korosensei42** [comment]
I don't know why the commits of @TimothyGillespie show up. However this should fix the error. Only some linterrors seem to occur. Gonna try fixing them right away

**Comment by Korosensei42** [comment]
@TimothyGillespie @RonjaKaehne The remaining lintererrors seem to be from files you worked on. Is it okay for you, if I fix them or would you like to do so on your own?

**Comment by TimothyGillespie** [comment]
It seems as though you have created a new branch from the tslint branch. I would rather delete this branch and make a new one from master since you would have to resolve merge conflicts with master.

Before you create a new branch do a git checkout master first (or the branch you want to make a copy off for a new branch)

**Comment by TimothyGillespie** [comment]
(Happened to me too that I would create a new branch from the wrong branch often enough)

**Comment by TimothyGillespie** [comment]
Also you could cherry pick commits to apply to the new branch so you wouldn't need to fo copy and paste. I just don't suggest this here since the new folder structur could potentially just cause a merge conflict again and you end up needing to copy paste anyway.

**Comment by Korosensei42** [comment]
I will try so. Thanks for the quick reply, @TimothyGillespie

**Pull request closed without merging**
